# Generated by Django 4.1.1 on 2022-11-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=64, verbose_name='회원아이디')),
                ('points', models.IntegerField(verbose_name='포인트')),
                ('reserved', models.CharField(choices=[('구매', '구매'), ('포인트취득', '포인트취득'), ('양수', '양수'), ('기타', '기타')], default='구매', max_length=64, verbose_name='적립구분')),
                ('consumed', models.CharField(choices=[('충전', '충전'), ('양도', '양도'), ('기타', '기타')], default='충전', max_length=64, verbose_name='사용구분')),
                ('status', models.CharField(choices=[('정상', '정상'), ('부족', '부족'), ('정지', '정지')], default='정상', max_length=64, verbose_name='적립상태')),
                ('method', models.CharField(max_length=64, verbose_name='적립또는사용수단')),
                ('register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': '충전가능금액',
                'verbose_name_plural': '충전가능금액',
                'db_table': 'evsp_budget',
            },
        ),
    ]
