# Generated by Django 4.1.1 on 2022-10-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charginginfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charginginfo',
            name='end_dttm',
            field=models.DateTimeField(verbose_name='충전완료일시'),
        ),
        migrations.AlterField(
            model_name='charginginfo',
            name='start_dttm',
            field=models.DateTimeField(verbose_name='충전시작일시'),
        ),
    ]
