# Generated by Django 4.1 on 2022-08-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpnumber', models.CharField(blank=True, max_length=64, verbose_name='충전기번호')),
                ('channel_name', models.CharField(blank=True, max_length=64, verbose_name='채널이름')),
                ('channel_status', models.CharField(blank=True, max_length=64, verbose_name='채널상태')),
                ('cp_status', models.CharField(blank=True, max_length=64, verbose_name='충전기상태')),
                ('connection_id', models.CharField(blank=True, max_length=256, verbose_name='커넥션아이디')),
            ],
            options={
                'verbose_name': '충전기채널',
                'verbose_name_plural': '충전기채널',
                'db_table': 'my_ocpp_clients',
            },
        ),
    ]
