# Generated by Django 4.1.1 on 2022-10-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='authorized_tag',
            field=models.CharField(default='00000001', max_length=64, verbose_name='승인된 카드테그'),
            preserve_default=False,
        ),
    ]
