# Generated by Django 4.1 on 2022-08-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocpp16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpname', models.CharField(blank=True, max_length=64)),
                ('consumer', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'CP커넥션',
                'verbose_name_plural': 'CP커넥션',
                'db_table': 'evsp_ocpp16',
            },
        ),
    ]
