# Generated by Django 4.1.1 on 2022-09-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcharger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcharger',
            name='connector_id_2',
        ),
        migrations.RemoveField(
            model_name='evcharger',
            name='connector_id_2_status',
        ),
        migrations.AddField(
            model_name='evcharger',
            name='connector_id_0',
            field=models.CharField(default='Available', max_length=64, verbose_name='0번커넥터아이디'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evcharger',
            name='connector_id_0_status',
            field=models.CharField(default='Available', max_length=64, verbose_name='0번커넥터상태'),
            preserve_default=False,
        ),
    ]
