# Generated by Django 4.1.1 on 2022-12-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcharger', '0003_alter_evcharger_cpname_alter_evcharger_cpstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcharger',
            name='mainuser_id',
            field=models.CharField(default='GRESystem', max_length=128, verbose_name='주사용자아이디'),
            preserve_default=False,
        ),
    ]
