# Generated by Django 4.1 on 2022-08-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=64, verbose_name='기준변수')),
                ('interval', models.IntegerField(null=True, verbose_name='확인주기')),
            ],
            options={
                'verbose_name': '운용변수',
                'verbose_name_plural': '운용변수',
                'db_table': 'evsp_variables',
            },
        ),
    ]
